apiVersion:  v1  #acts a manuall to your system
kind: Pod
metadata:  #like a tag , all the letter shuold be in lowercase
        name: mypod
spec:
 containers:
    - name: mypod-cont
      image: nginx:latest
      resources: 
          requests:
            cpu: "50m"
            memory: "90Mi"        
      ports:  
        - name: http
          containerPort: 80
          protocol: TCP
