apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-blue
  labels:
    app: my-app-blue
    version: blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app-blue
      version: blue
  template:
    metadata:
      labels:
        app: my-app-blue
        version: blue
    spec:
      containers:
      - name: my-app-container
        image: tomcat:9  # old version
        ports:
        - containerPort: 80
