apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-deployment-$ TARGET_ROLE=blue
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: tomcat
        role: $ TARGET_ROLE=blue
    spec:
      containers:
      - name: tomcat-container
        image: tomcat:latest
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /
            port: 8080