apiVersion: apps/v1
kind: Deployment
metadata:
    name: akash 
    labels:
          akash
spec:
    replicas: 10
    strategy: 
        type: RollingUpdate
        rollingUpdate:
          maxSurge: 2   # Maximum number of pods that can be created over the desired replicas
          maxUnavailable: 2  # Maximum number of pods that can be unavailable during the update 
    template:
          metadata: 
                name: akash 
                labels:
                      app: akash
          spec:
              containers:
                  - name: http
                    image: tomcat 
                    ports:
                        - name: http
                          containerPort: 80
                          protocol: TCP      
    selector:
        matchLabels:
            app: akash 
