apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-green
  labels:
    app: my-app-green
    version: green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app-green
      version: green
  template:
    metadata:
      labels:
        app: my-app-green
        version: green
    spec:
      containers:
      - name: my-app-container
        image: tomcat:9  # New version
        ports:
        - containerPort: 80
