apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  selector:
    app: my-app-green
    version: green  # Now pointing to the green version
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
