apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: oneingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: a3ee86dd065064d83a3f2c1bfcb293fa-309622677.us-east-1.elb.amazonaws.com
    http:
      paths:
        
         -  path: /todo
            pathType: Prefix
            backend:
              service: 
                name: frontendsrv
                port:
                  number: 80
         -  path: /employee
            pathType: Prefix
            backend:
              service: 
                name: backendsrv
                port:
                  number: 8080
  