apiVersion: v1
kind: Service
metadata: 
  name: frontendsrv
spec:
  type: ClusterIP
  selector:
    app: deployappfront 
  ports:
    - port: 8080
      targetPort: 8080
      name: http
      protocol: TCP