apiVersion: v1
kind: Service
metadata:
  name: tomcat-service
  labels:
    app: tomcat
    role: $ TARGET_ROLE=blue
    env: prod
spec:
  type: LoadBalancer
  selector:
    app: tomcat
    role: $ TARGET_ROLE=blue
  ports:
    - port: 80
      targetPort: 8080