apiVersion: apps/v1
kind: StatefulSet 
metadata: 
       name: state
       labels:
            app: state
spec: 
    replicas: 5  #how many replica's you want to create on the basis of template
    template:
      metadata:  #like a tag
         name: state
         labels: 
            app: state
      spec:
        containers:
            - name: mypodss-cont
              image: mysql:latest
              resources: 
                  requests:
                    cpu: "50m"
                    memory: "90Mi"        
              ports:  
                - name: dbport
                  containerPort: 3306
                  protocol: TCP
              env:
                - name: MYSQL_ROOT_PASSWORD
                  valueFrom:
                          configMapKeyRef:
                              name: configmap
                              key: DB_PASSWORD 
                - name: MYSQL_USER_NAME
                  valueFrom:
                          configMapKeyRef:
                              name: configmap
                              key: DB_USER 
                          
    selector:
        matchLabels:
          app: state